# Generated by Django 4.1.7 on 2023-03-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mentorizon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mentor_sphere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="mentorizon.sphere",
            ),
        ),
    ]
