# Generated by Django 4.1.7 on 2023-03-03 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorizon", "0004_alter_user_mentor_sphere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingvote",
            name="rate",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[django.core.validators.MinValueValidator(limit_value=0.0)],
            ),
        ),
    ]
