# Generated by Django 4.1.7 on 2023-03-04 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorizon", "0005_alter_ratingvote_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingvote",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0),
                    django.core.validators.MaxValueValidator(limit_value=5),
                ]
            ),
        ),
    ]
