# Generated by Django 4.1.7 on 2023-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorizon", "0007_remove_sphere_name_unique_sphere_name_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ratingvote",
            constraint=models.UniqueConstraint(
                fields=("rating", "voter"), name="vote_unique"
            ),
        ),
    ]
